//
// Ask.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Ask: Codable {

    public var fullname: String?
    public var email: String?
    public var description: String?
    public var id: Double?
    public var createdAt: Date?
    public var updatedAt: Date?


    
    public init(fullname: String? = nil, email: String? = nil, description: String? = nil, id: Double? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.fullname = fullname
        self.email = email
        self.description = description
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(fullname, forKey: "fullname")
        try container.encodeIfPresent(email, forKey: "email")
        try container.encodeIfPresent(description, forKey: "description")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(createdAt, forKey: "createdAt")
        try container.encodeIfPresent(updatedAt, forKey: "updatedAt")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        fullname = try container.decodeIfPresent(String.self, forKey: "fullname")
        email = try container.decodeIfPresent(String.self, forKey: "email")
        description = try container.decodeIfPresent(String.self, forKey: "description")
        id = try container.decodeIfPresent(Double.self, forKey: "id")
        createdAt = try container.decodeIfPresent(Date.self, forKey: "createdAt")
        updatedAt = try container.decodeIfPresent(Date.self, forKey: "updatedAt")
    }
}

