//
// Faq.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Faq: Codable {

    public var question: String?
    public var answers: String?
    public var kind: String?
    public var id: Double?
    public var createdAt: Date?
    public var updatedAt: Date?


    
    public init(question: String? = nil, answers: String? = nil, kind: String? = nil, id: Double? = nil, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.question = question
        self.answers = answers
        self.kind = kind
        self.id = id
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(question, forKey: "question")
        try container.encodeIfPresent(answers, forKey: "answers")
        try container.encodeIfPresent(kind, forKey: "kind")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(createdAt, forKey: "createdAt")
        try container.encodeIfPresent(updatedAt, forKey: "updatedAt")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        question = try container.decodeIfPresent(String.self, forKey: "question")
        answers = try container.decodeIfPresent(String.self, forKey: "answers")
        kind = try container.decodeIfPresent(String.self, forKey: "kind")
        id = try container.decodeIfPresent(Double.self, forKey: "id")
        createdAt = try container.decodeIfPresent(Date.self, forKey: "createdAt")
        updatedAt = try container.decodeIfPresent(Date.self, forKey: "updatedAt")
    }
}

