//
// InlineResponse2003.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class InlineResponse2003: Codable {

    public var undefined: JSON?


    
    public init(undefined: JSON? = nil) {
        self.undefined = undefined
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(undefined, forKey: "undefined")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        undefined = try container.decodeIfPresent(JSON.self, forKey: "undefined")
    }
}

